/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misframes;

import java.awt.Color;
import java.awt.Dimension;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class Consulta11Comida extends javax.swing.JFrame {
    private int ind;
    /**
     * Creates new form Consulta10Comida
     */
    public Consulta11Comida() {
        initComponents();
        ind=1;
        this.setTitle("Restaurante");
        this.setSize(1020, 640);
        this.setMinimumSize(new Dimension(1020,640));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelSlogan = new javax.swing.JLabel();
        jPanelDerecha = new javax.swing.JPanel();
        jButtonSiguiente = new javax.swing.JButton();
        jPanelSur = new javax.swing.JPanel();
        jButtonRegresa = new javax.swing.JButton();
        jPanelIzquierda = new javax.swing.JPanel();
        jButtonAnterior = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabelTipoComida = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabelComida1 = new javax.swing.JLabel();
        jLabelComida2 = new javax.swing.JLabel();
        jLabelComida3 = new javax.swing.JLabel();
        jLabelComida4 = new javax.swing.JLabel();
        jLabelComida5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabelTitulo.setBackground(new java.awt.Color(153, 255, 153));
        jLabelTitulo.setFont(new java.awt.Font("Elephant", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(102, 102, 0));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hotelversioncircular.png"))); // NOI18N
        jLabelTitulo.setText("Restaurante Wolfsburg");
        jLabelTitulo.setOpaque(true);
        jPanel1.add(jLabelTitulo, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabelSlogan.setBackground(new java.awt.Color(255, 255, 102));
        jLabelSlogan.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabelSlogan.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSlogan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSlogan.setText("!TE OFRECEMOS VARIEDAD DE COMIDA! CON LA GASTRONOMIA CARACTERISTICA DE NUESTRO ESTADO");
        jLabelSlogan.setOpaque(true);
        jPanel2.add(jLabelSlogan, java.awt.BorderLayout.PAGE_START);

        jPanelDerecha.setBackground(new java.awt.Color(153, 255, 204));
        jPanelDerecha.setLayout(new javax.swing.BoxLayout(jPanelDerecha, javax.swing.BoxLayout.LINE_AXIS));

        jButtonSiguiente.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButtonSiguiente.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Siguiente.png"))); // NOI18N
        jButtonSiguiente.setText("Siguiente");
        jButtonSiguiente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSiguiente.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSiguienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSiguienteMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonSiguienteMouseReleased(evt);
            }
        });
        jPanelDerecha.add(jButtonSiguiente);

        jPanel2.add(jPanelDerecha, java.awt.BorderLayout.LINE_END);

        jPanelSur.setBackground(new java.awt.Color(204, 204, 204));
        jPanelSur.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButtonRegresa.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButtonRegresa.setForeground(new java.awt.Color(0, 0, 0));
        jButtonRegresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Regresa.png"))); // NOI18N
        jButtonRegresa.setText("Regresar");
        jButtonRegresa.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonRegresa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegresa.setPreferredSize(new java.awt.Dimension(150, 40));
        jButtonRegresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonRegresaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonRegresaMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonRegresaMouseReleased(evt);
            }
        });
        jPanelSur.add(jButtonRegresa);

        jPanel2.add(jPanelSur, java.awt.BorderLayout.PAGE_END);

        jPanelIzquierda.setBackground(new java.awt.Color(153, 255, 204));
        jPanelIzquierda.setLayout(new javax.swing.BoxLayout(jPanelIzquierda, javax.swing.BoxLayout.LINE_AXIS));

        jButtonAnterior.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButtonAnterior.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Regresa.png"))); // NOI18N
        jButtonAnterior.setText("Anterior");
        jButtonAnterior.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAnterior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAnterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAnteriorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAnteriorMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonAnteriorMouseReleased(evt);
            }
        });
        jPanelIzquierda.add(jButtonAnterior);

        jPanel2.add(jPanelIzquierda, java.awt.BorderLayout.LINE_START);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabelTipoComida.setBackground(new java.awt.Color(153, 255, 204));
        jLabelTipoComida.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        jLabelTipoComida.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTipoComida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTipoComida.setText("Sushi");
        jLabelTipoComida.setOpaque(true);
        jPanel6.add(jLabelTipoComida, java.awt.BorderLayout.PAGE_START);
        jPanel6.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setPreferredSize(new java.awt.Dimension(571, 50));

        jLabelComida1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabelComida1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelComida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Uramaki.jpg"))); // NOI18N
        jLabelComida1.setText("Umaraki");
        jLabelComida1.setFocusable(false);
        jLabelComida1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelComida1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel4.add(jLabelComida1);

        jLabelComida2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabelComida2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelComida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Maki.jpg"))); // NOI18N
        jLabelComida2.setText("Maki");
        jLabelComida2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelComida2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel4.add(jLabelComida2);

        jLabelComida3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabelComida3.setForeground(new java.awt.Color(0, 0, 0));
        jLabelComida3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Nigiri.jpg"))); // NOI18N
        jLabelComida3.setText("Nigiri");
        jLabelComida3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelComida3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel4.add(jLabelComida3);

        jLabelComida4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabelComida4.setForeground(new java.awt.Color(0, 0, 0));
        jLabelComida4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Temaki.jpg"))); // NOI18N
        jLabelComida4.setText("Temaki");
        jLabelComida4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelComida4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel4.add(jLabelComida4);

        jLabelComida5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabelComida5.setForeground(new java.awt.Color(0, 0, 0));
        jLabelComida5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Gohan.jpg"))); // NOI18N
        jLabelComida5.setText("Gohan");
        jLabelComida5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelComida5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel4.add(jLabelComida5);

        jPanel6.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel6, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSiguienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSiguienteMouseEntered
        // TODO add your handling code here:
        this.jButtonSiguiente.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButtonSiguienteMouseEntered

    private void jButtonSiguienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSiguienteMouseExited
        // TODO add your handling code here:
        this.jButtonSiguiente.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButtonSiguienteMouseExited

    private void jButtonSiguienteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSiguienteMouseReleased
        // TODO add your handling code here:
        if(this.ind==1){
            this.jLabelTipoComida.setText("A la mexicana");
            jLabelComida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TortaChilaquiles.jpg"))); // NOI18N
            jLabelComida1.setText("Torta de chilaquiles");
             jLabelComida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TacosCanasta.jpg"))); // NOI18N
            jLabelComida2.setText("Tacos de canasta");
             jLabelComida3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Flautas.jpg"))); // NOI18N
            jLabelComida3.setText("Flautas");
             jLabelComida4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Barbacoa.jpg"))); // NOI18N
            jLabelComida4.setText("Barbacoa");
             jLabelComida5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ChilesRellenos.jpg"))); // NOI18N
            jLabelComida5.setText("Chiles rellenos");
            
            this.ind=3;
        }else if(this.ind==2){
            this.jLabelTipoComida.setText("Sushi");
             jLabelComida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Uramaki.jpg"))); // NOI18N
            jLabelComida1.setText("Umaraki");
            jLabelComida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Maki.jpg"))); // NOI18N
            jLabelComida2.setText("Maki");
            jLabelComida3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Nigiri.jpg"))); // NOI18N
            jLabelComida3.setText("Nigiri");
             jLabelComida4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Temaki.jpg"))); // NOI18N
             jLabelComida4.setText("Temaki");
             jLabelComida5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Gohan.jpg"))); // NOI18N
             jLabelComida5.setText("Gohan");
      
            this.ind=1;
        }else if(this.ind==3){
             this.jLabelTipoComida.setText("Bebidas");
             jLabelComida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Atole.jpg"))); // NOI18N
            jLabelComida1.setText("Atole");
            jLabelComida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agua_Limon.jpg"))); // NOI18N
            jLabelComida2.setText("Agua de limon");
            jLabelComida3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Torito.jpg"))); // NOI18N
            jLabelComida3.setText("Torito");
             jLabelComida4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tequila.jpg"))); // NOI18N
             jLabelComida4.setText("Tequila");
             jLabelComida5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pozol.jpg"))); // NOI18N
             jLabelComida5.setText("Pozol");
            
            this.ind=4;
        }else if(this.ind==4){
             this.jLabelTipoComida.setText("Bebidas");
             jLabelComida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PinaColada.jpg"))); // NOI18N
            jLabelComida1.setText("Piña colada");
            jLabelComida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Margarita.jpg"))); // NOI18N
            jLabelComida2.setText("Margarita");
            jLabelComida3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/horchata.jpg"))); // NOI18N
            jLabelComida3.setText("Agua de horchata");
             jLabelComida4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/chocolate.jpg"))); // NOI18N
             jLabelComida4.setText("Chocolate");
             jLabelComida5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cerveza.jpg"))); // NOI18N
             jLabelComida5.setText("Cerveza");
            
            
            
            this.ind=2;
        }
        
        
    }//GEN-LAST:event_jButtonSiguienteMouseReleased

    private void jButtonRegresaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegresaMouseEntered
        // TODO add your handling code here:
        this.jButtonRegresa.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButtonRegresaMouseEntered

    private void jButtonRegresaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegresaMouseExited
        // TODO add your handling code here:
        this.jButtonRegresa.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButtonRegresaMouseExited

    private void jButtonAnteriorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAnteriorMouseEntered
        // TODO add your handling code here:
        this.jButtonAnterior.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButtonAnteriorMouseEntered

    private void jButtonAnteriorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAnteriorMouseExited
        // TODO add your handling code here:
        this.jButtonAnterior.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButtonAnteriorMouseExited

    private void jButtonRegresaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegresaMouseReleased
        // TODO add your handling code here:
        this.dispose();
        new MenuConsultas().setVisible(true);
    }//GEN-LAST:event_jButtonRegresaMouseReleased

    private void jButtonAnteriorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAnteriorMouseReleased
        // TODO add your handling code here:
          if(this.ind==1){
              this.jLabelTipoComida.setText("Bebidas");
             jLabelComida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PinaColada.jpg"))); // NOI18N
            jLabelComida1.setText("Piña colada");
            jLabelComida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Margarita.jpg"))); // NOI18N
            jLabelComida2.setText("Margarita");
            jLabelComida3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/horchata.jpg"))); // NOI18N
            jLabelComida3.setText("Agua de horchata");
             jLabelComida4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/chocolate.jpg"))); // NOI18N
             jLabelComida4.setText("Chocolate");
             jLabelComida5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cerveza.jpg"))); // NOI18N
             jLabelComida5.setText("Cerveza");
            
              
              
            
            this.ind=3;
        }else if(this.ind==2){
            this.jLabelTipoComida.setText("Sushi");
             jLabelComida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Uramaki.jpg"))); // NOI18N
            jLabelComida1.setText("Umaraki");
            jLabelComida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Maki.jpg"))); // NOI18N
            jLabelComida2.setText("Maki");
            jLabelComida3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Nigiri.jpg"))); // NOI18N
            jLabelComida3.setText("Nigiri");
             jLabelComida4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Temaki.jpg"))); // NOI18N
             jLabelComida4.setText("Temaki");
             jLabelComida5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Gohan.jpg"))); // NOI18N
             jLabelComida5.setText("Gohan");
      
            this.ind=1;
        }else if(this.ind==3){
             this.jLabelTipoComida.setText("Bebidas");
             jLabelComida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Atole.jpg"))); // NOI18N
            jLabelComida1.setText("Atole");
            jLabelComida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agua_Limon.jpg"))); // NOI18N
            jLabelComida2.setText("Agua de limon");
            jLabelComida3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Torito.jpg"))); // NOI18N
            jLabelComida3.setText("Torito");
             jLabelComida4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tequila.jpg"))); // NOI18N
             jLabelComida4.setText("Tequila");
             jLabelComida5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pozol.jpg"))); // NOI18N
             jLabelComida5.setText("Pozol");
            
            this.ind=4;
        }else if(this.ind==4){
              
            this.jLabelTipoComida.setText("A la mexicana");
            jLabelComida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TortaChilaquiles.jpg"))); // NOI18N
            jLabelComida1.setText("Torta de chilaquiles");
             jLabelComida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TacosCanasta.jpg"))); // NOI18N
            jLabelComida2.setText("Tacos de canasta");
             jLabelComida3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Flautas.jpg"))); // NOI18N
            jLabelComida3.setText("Flautas");
             jLabelComida4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Barbacoa.jpg"))); // NOI18N
            jLabelComida4.setText("Barbacoa");
             jLabelComida5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ChilesRellenos.jpg"))); // NOI18N
            jLabelComida5.setText("Chiles rellenos");
             
            
            
            this.ind=2;
        }
        
        
        
    }//GEN-LAST:event_jButtonAnteriorMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulta11Comida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta11Comida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta11Comida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulta11Comida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consulta11Comida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonRegresa;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JLabel jLabelComida1;
    private javax.swing.JLabel jLabelComida2;
    private javax.swing.JLabel jLabelComida3;
    private javax.swing.JLabel jLabelComida4;
    private javax.swing.JLabel jLabelComida5;
    private javax.swing.JLabel jLabelSlogan;
    private javax.swing.JLabel jLabelTipoComida;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelDerecha;
    private javax.swing.JPanel jPanelIzquierda;
    private javax.swing.JPanel jPanelSur;
    // End of variables declaration//GEN-END:variables
}
