/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misframes;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.RenderingHints.Key;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import misclases.MySqlConn;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class Consulta7 extends javax.swing.JFrame {
    
    private MySqlConn conn;
  /*  private JPanel panel;
    private JButton jButtonReg;
    private ImageIcon iconoReg;
    private JTextField jTextFieldNombre,jTextFieldPiso,jTextFieldHabitacion,jTextFieldBusca;
    private JLabel jLabelNombre,jLabelPiso,jLabelHabitacion,jLabeBusca;
    */
    
    /**
     * Creates new form Consulta7
     */
    public Consulta7() {
        this.conn=new MySqlConn();
        initComponents();
        
       this.setSize(1020, 640);
       this.setMinimumSize(new Dimension(1020,640));
       this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldBusca = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButtonReg = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableInfo = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("consulta habitacion y piso de huesped");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jLabelNombre.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabelNombre.setText("Ingresa nombre del huesped.Presiona enter para confirmar");
        jPanel4.add(jLabelNombre);

        jTextFieldBusca.setPreferredSize(new java.awt.Dimension(150, 24));
        jTextFieldBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBuscaKeyReleased(evt);
            }
        });
        jPanel4.add(jTextFieldBusca);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        jButtonReg.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButtonReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Regresa.png"))); // NOI18N
        jButtonReg.setText("Regresar");
        jButtonReg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonReg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonRegMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonRegMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonRegMouseReleased(evt);
            }
        });
        jPanel3.add(jButtonReg, java.awt.BorderLayout.WEST);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jTableInfo.setBackground(new java.awt.Color(153, 255, 204));
        jTableInfo.setForeground(new java.awt.Color(0, 0, 0));
        jTableInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "No.Habitación", "Piso"
            }
        ));
        jScrollPane2.setViewportView(jTableInfo);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscaKeyReleased
        // TODO add your handling code here:
        String nombre=this.jTextFieldBusca.getText();
        String query="select * from habitacion where nombre='"+nombre+"'";
        int habitacion,piso;
        String nom="";
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        try{
            this.conn.Consult(query);
            int n=0;
            this.conn.rs.last();
            n=this.conn.rs.getRow();
            this.conn.rs.first();
           
            if(n>0){
              
                Object obj[][]=new Object[1][3];
                obj[0][0]=this.conn.rs.getString(14);
                obj[0][1]=this.conn.rs.getInt(1);
                obj[0][2]=this.conn.rs.getInt(13);

                String columnas[]={"Nombre","No.Habitación","Piso"};
                this.jTableInfo.setModel(new DefaultTableModel(obj,columnas));
                
                
            }else{
                JOptionPane.showMessageDialog(this, "No existen registros con ese nombre");
            }
            
            
        }catch(Exception ex){
            
            
        }
        }
        
        
    }//GEN-LAST:event_jTextFieldBuscaKeyReleased

    private void jButtonRegMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegMouseEntered
        // TODO add your handling code here:
        jButtonReg.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButtonRegMouseEntered

    private void jButtonRegMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegMouseExited
        // TODO add your handling code here:
         jButtonReg.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButtonRegMouseExited

    private void jButtonRegMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegMouseReleased
        // TODO add your handling code here:
        dispose();
         new MenuConsultas().setVisible(true);
        
        
    }//GEN-LAST:event_jButtonRegMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulta7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulta7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consulta7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonReg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableInfo;
    private javax.swing.JTextField jTextFieldBusca;
    // End of variables declaration//GEN-END:variables
}
