/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misframes;

import java.awt.Color;
import java.awt.Dimension;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class Consulta1 extends javax.swing.JFrame {
    private int indicador;
    private Clip clip;
    /**
     * Creates new form Consulta1
     */
    public Consulta1() {
        this.indicador=1;
        initComponents();
        iniciaClip();
        this.setSize(1100, 640);
        this.setMinimumSize(new Dimension(1100,640));
        this.setLocationRelativeTo(null);
    }
    private void iniciaClip(){
        
        try{
            
            this.clip=AudioSystem.getClip();
            this.clip.open(AudioSystem.getAudioInputStream(getClass().getResourceAsStream("/cancion/FondoPrin.wav")));
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error con archivo de audio");
            
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButtonAnterior = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButtonPlay = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButtonSiguiente = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButtonStop = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabelImagen1 = new javax.swing.JLabel();
        jLabelImagen2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitulo.setBackground(new java.awt.Color(153, 255, 204));
        jLabelTitulo.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hotelversioncircular.png"))); // NOI18N
        jLabelTitulo.setText("GALERIA");
        jLabelTitulo.setOpaque(true);
        getContentPane().add(jLabelTitulo, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Regresa.png"))); // NOI18N
        jButton1.setText("Regresar");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jPanel1.add(jButton1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        jPanel4.setLayout(flowLayout1);

        jButtonAnterior.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButtonAnterior.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Regresa.png"))); // NOI18N
        jButtonAnterior.setText("Anterior");
        jButtonAnterior.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAnterior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAnterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAnteriorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAnteriorMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonAnteriorMouseReleased(evt);
            }
        });
        jPanel4.add(jButtonAnterior);

        jPanel2.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jButtonPlay.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButtonPlay.setForeground(new java.awt.Color(0, 0, 0));
        jButtonPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sonidosuena.png"))); // NOI18N
        jButtonPlay.setText("Play");
        jButtonPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPlay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPlay.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonPlayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonPlayMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonPlayMouseReleased(evt);
            }
        });
        jPanel5.add(jButtonPlay);

        jPanel2.add(jPanel5);

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));

        jButtonSiguiente.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButtonSiguiente.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Siguiente.png"))); // NOI18N
        jButtonSiguiente.setText("Siguiente");
        jButtonSiguiente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSiguiente.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSiguienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSiguienteMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonSiguienteMouseReleased(evt);
            }
        });
        jPanel6.add(jButtonSiguiente);

        jPanel3.add(jPanel6);

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jButtonStop.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButtonStop.setForeground(new java.awt.Color(0, 0, 0));
        jButtonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sonidosilen.png"))); // NOI18N
        jButtonStop.setText("Stop");
        jButtonStop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonStop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonStop.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonStopMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonStopMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonStopMouseReleased(evt);
            }
        });
        jPanel7.add(jButtonStop);

        jPanel3.add(jPanel7);

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_END);

        jPanel8.setBackground(new java.awt.Color(204, 204, 255));

        jLabelImagen1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabelImagen1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelImagen1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tipo1 (1).jpg"))); // NOI18N
        jLabelImagen1.setText("Habitacion sencilla");
        jLabelImagen1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabelImagen1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelImagen1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel8.add(jLabelImagen1);

        jLabelImagen2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabelImagen2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelImagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tipo2 (1).jpg"))); // NOI18N
        jLabelImagen2.setText("Habitacion doble");
        jLabelImagen2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelImagen2.setVerifyInputWhenFocusTarget(false);
        jLabelImagen2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel8.add(jLabelImagen2);

        getContentPane().add(jPanel8, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSiguienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSiguienteMouseEntered
        // TODO add your handling code here:
        this.jButtonSiguiente.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButtonSiguienteMouseEntered

    private void jButtonSiguienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSiguienteMouseExited
        // TODO add your handling code here:
        this.jButtonSiguiente.setBackground(Color.LIGHT_GRAY);
    
    }//GEN-LAST:event_jButtonSiguienteMouseExited

    private void jButtonSiguienteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSiguienteMouseReleased
        // TODO add your handling code here:
        this.indicador++;
        if(this.indicador>5){
            this.indicador=1;
        }
        if(this.indicador==1){
            this.jLabelImagen1.setIcon(new ImageIcon(getClass().getResource("/imagenes/tipo1 (1).jpg")));
            this.jLabelImagen1.setText("Habitacion sencilla");
            this.jLabelImagen2.setIcon(new ImageIcon(getClass().getResource("/imagenes/tipo2 (1).jpg")));
            this.jLabelImagen2.setText("Habitacion doble");
            
            
            
        }else if(this.indicador==2){
            
            this.jLabelImagen1.setIcon(new ImageIcon(getClass().getResource("/imagenes/tipo3 (1).jpg")));
            this.jLabelImagen1.setText("Habitacion triple");
            this.jLabelImagen2.setIcon(new ImageIcon(getClass().getResource("/imagenes/gimnasio (1).jpg")));
            this.jLabelImagen2.setText("Gimnasio");
            
           
        }else if(this.indicador==3){
            this.jLabelImagen1.setIcon(new ImageIcon(getClass().getResource("/imagenes/spa (1).jpg")));
            this.jLabelImagen1.setText("Spa");
            this.jLabelImagen2.setIcon(new ImageIcon(getClass().getResource("/imagenes/alberca (1).jpg")));
            this.jLabelImagen2.setText("Alberca");
            
            
        
        }else if(this.indicador==4){
            
            this.jLabelImagen1.setIcon(new ImageIcon(getClass().getResource("/imagenes/lavanderia (1).jpg")));
            this.jLabelImagen1.setText("Lavanderia");
            this.jLabelImagen2.setIcon(new ImageIcon(getClass().getResource("/imagenes/baños (1).jpg")));
            this.jLabelImagen2.setText("Baños");
            
            
          
        }else if(this.indicador==5){
            this.jLabelImagen1.setIcon(new ImageIcon(getClass().getResource("/imagenes/estacionamiento (1).jpg")));
            this.jLabelImagen1.setText("Estacionamiento");
            this.jLabelImagen2.setIcon(new ImageIcon(getClass().getResource("/imagenes/restaurante (1).jpg")));
            this.jLabelImagen2.setText("Restaurante");
            
            
          
        }
        
        
    }//GEN-LAST:event_jButtonSiguienteMouseReleased

    private void jButtonAnteriorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAnteriorMouseEntered
        // TODO add your handling code here:
        this.jButtonAnterior.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButtonAnteriorMouseEntered

    private void jButtonAnteriorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAnteriorMouseExited
        // TODO add your handling code here:
        this.jButtonAnterior.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButtonAnteriorMouseExited

    private void jButtonAnteriorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAnteriorMouseReleased
        // TODO add your handling code here:
             this.indicador--;
        if(this.indicador<1){
            this.indicador=5;
        }
        if(this.indicador==1){
            this.jLabelImagen1.setIcon(new ImageIcon(getClass().getResource("/imagenes/tipo1 (1).jpg")));
            this.jLabelImagen1.setText("Habitacion sencilla");
            this.jLabelImagen2.setIcon(new ImageIcon(getClass().getResource("/imagenes/tipo2 (1).jpg")));
            this.jLabelImagen2.setText("Habitacion doble");
            
            
            
        }else if(this.indicador==2){
            
            this.jLabelImagen1.setIcon(new ImageIcon(getClass().getResource("/imagenes/tipo3 (1).jpg")));
            this.jLabelImagen1.setText("Habitacion triple");
            this.jLabelImagen2.setIcon(new ImageIcon(getClass().getResource("/imagenes/gimnasio (1).jpg")));
            this.jLabelImagen2.setText("Gimnasio");
            
           
        }else if(this.indicador==3){
            this.jLabelImagen1.setIcon(new ImageIcon(getClass().getResource("/imagenes/spa (1).jpg")));
            this.jLabelImagen1.setText("Spa");
            this.jLabelImagen2.setIcon(new ImageIcon(getClass().getResource("/imagenes/alberca (1).jpg")));
            this.jLabelImagen2.setText("Alberca");
            
            
        
        }else if(this.indicador==4){
            
            this.jLabelImagen1.setIcon(new ImageIcon(getClass().getResource("/imagenes/lavanderia (1).jpg")));
            this.jLabelImagen1.setText("Lavanderia");
            this.jLabelImagen2.setIcon(new ImageIcon(getClass().getResource("/imagenes/baños (1).jpg")));
            this.jLabelImagen2.setText("Baños");
            
            
          
        }else if(this.indicador==5){
            this.jLabelImagen1.setIcon(new ImageIcon(getClass().getResource("/imagenes/estacionamiento (1).jpg")));
            this.jLabelImagen1.setText("Estacionamiento");
            this.jLabelImagen2.setIcon(new ImageIcon(getClass().getResource("/imagenes/restaurante (1).jpg")));
            this.jLabelImagen2.setText("Restaurante");
            
            
          
        }
        
    }//GEN-LAST:event_jButtonAnteriorMouseReleased

    private void jButtonPlayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPlayMouseEntered
        // TODO add your handling code here:
        this.jButtonPlay.setBackground(Color.yellow);
    }//GEN-LAST:event_jButtonPlayMouseEntered

    private void jButtonPlayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPlayMouseExited
        // TODO add your handling code here:
        this.jButtonPlay.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButtonPlayMouseExited

    private void jButtonPlayMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPlayMouseReleased
        // TODO add your handling code here:
        clip.start();
        
    }//GEN-LAST:event_jButtonPlayMouseReleased

    private void jButtonStopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonStopMouseEntered
        // TODO add your handling code here:
        this.jButtonStop.setBackground(Color.yellow);
    }//GEN-LAST:event_jButtonStopMouseEntered

    private void jButtonStopMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonStopMouseExited
        // TODO add your handling code here:
        this.jButtonStop.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButtonStopMouseExited

    private void jButtonStopMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonStopMouseReleased
        // TODO add your handling code here:
        clip.stop();
    }//GEN-LAST:event_jButtonStopMouseReleased

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        this.jButton1.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        this.jButton1.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        // TODO add your handling code here:
        this.dispose();
        new MenuConsultas().setVisible(true);
    }//GEN-LAST:event_jButton1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consulta1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonPlay;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JButton jButtonStop;
    private javax.swing.JLabel jLabelImagen1;
    private javax.swing.JLabel jLabelImagen2;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
