/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misframes;

import java.awt.BorderLayout;
import java.awt.Dimension;
import misclases.MySqlConn;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author elimtzxd
 */
public class HabPorcentajes extends javax.swing.JFrame {
    private MySqlConn conn;
        
    private int contadors=0, contadord=0, contadort=0;
    private int sencilla, doble, triple;
    private double porcentaje[]=new double[3];
    
    /**
     * Creates new form HabPorcentajes
     */
    public HabPorcentajes() {
        initComponents();
    }

    public HabPorcentajes(MySqlConn conn) {
        this.conn = conn;
        initComponents();
        mostrarGrafica();
    }
    
    public void mostrarGrafica(){
        ConsultaHab();
        ConsultaTotalHab();
        CalcularPorcentaje();
        
        
        DefaultCategoryDataset datos= new DefaultCategoryDataset();
        datos.addValue(this.porcentaje[0], "Sencilla", "Sencilla");
        datos.addValue(this.porcentaje[1], "Doble", "Doble");
        datos.addValue(this.porcentaje[2], "Triple", "Triple");
        JFreeChart graficos=ChartFactory.createBarChart3D("PORCENTAJE POR TIPO DE HABITACION", "Tipos de habitacion", "Porcentaje de ocupacion", datos, PlotOrientation.VERTICAL, true, true, false);
        ChartPanel mypanel=new ChartPanel(graficos);
        mypanel.setPreferredSize(new Dimension(jPanel1.getSize().width,jPanel1.getSize().height));
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(mypanel,BorderLayout.NORTH);
        pack();
        repaint();
    }
    
    private void ConsultaHab(){
        String query="select * from habitacion";
        this.conn.Consult(query);
        int n=0;
        
        try{
            this.conn.rs.last();
            n=this.conn.rs.getRow();
            this.conn.rs.first();
        }catch(Exception e){
            System.out.println("Error 1");
        }
        if (n!=0) {
            for (int i = 0; i < n; i++) {
            
                try{ 
                    if (this.conn.rs.getInt(10)==1) {
                        this.contadors++;
                    }else if(this.conn.rs.getInt(10)==2){
                        this.contadord++;
                    }else if(this.conn.rs.getInt(10)==3){
                        this.contadort++;
                    }
                    this.conn.rs.next();
                   
                    
                }catch(Exception e){
                    System.out.println("Error 2");
                }
            }
            }
    }
    
    private void CalcularPorcentaje(){
        
        this.porcentaje[0]=((double) this.contadors * 100.0)/this.sencilla;
        this.porcentaje[1]=((double) this.contadord * 100.0)/this.doble;
        this.porcentaje[2]=((double) this.contadort * 100.0)/this.triple;
       /* System.out.println(this.porcentaje[0]);
        System.out.println(this.porcentaje[1]);
        System.out.println(this.porcentaje[2]);
        System.out.println(this.contadors);
        System.out.println(this.contadord);
        System.out.println(this.contadort);
        System.out.println(this.sencilla);
        System.out.println(this.doble);
        System.out.println(this.triple); */
    }
    
private void ConsultaTotalHab(){
    String query="select * from contadoreshab where sencilla='" +9+"'";
        this.conn.Consult(query);
        int n=0;
        try{
            this.conn.rs.last();
            n=this.conn.rs.getRow();
            this.conn.rs.first();
        }catch(Exception e){
            System.out.println("Error 1");
        }
        
                try{
                   this.sencilla=conn.rs.getInt(1);
                   this.doble=conn.rs.getInt(2);
                   this.triple=conn.rs.getInt(3);
                }catch(Exception e){
                    System.out.println("Error 2");
                
        }
}    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HabPorcentajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HabPorcentajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HabPorcentajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HabPorcentajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HabPorcentajes(new MySqlConn()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
