/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misframes;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import misclases.Fondo;
import misclases.Hotel;


/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class Portada extends javax.swing.JFrame  {

    /**
     * Creates new form Portada
     */
    public Portada() {
            new Hotel();
            initComponents();
            this.setTitle("PORTADA");
                      
            Fondo fondo=new Fondo();
            jPanelFondo.add(fondo,BorderLayout.CENTER);
             jPanelFondo.repaint();
            this.setSize(1020, 640);
            this.setLocationRelativeTo(null);
        
    }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jPanelFondo = new javax.swing.JPanel();
        jButtonContinuar = new java.awt.Button();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelFondo.setLayout(new java.awt.BorderLayout());

        jButtonContinuar.setBackground(new java.awt.Color(102, 255, 204));
        jButtonContinuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonContinuar.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jButtonContinuar.setLabel("Continuar -->");
        jButtonContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonContinuarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonContinuarMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonContinuarMouseReleased(evt);
            }
        });
        jPanelFondo.add(jButtonContinuar, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanelFondo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonContinuarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonContinuarMouseReleased
        
       this.dispose();
        new LogIn().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButtonContinuarMouseReleased

    private void jButtonContinuarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonContinuarMouseEntered
        //System.out.println(Hotel.habitaciones);
        jButtonContinuar.setBackground(Color.PINK);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonContinuarMouseEntered

    private void jButtonContinuarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonContinuarMouseExited
        jButtonContinuar.setBackground(new java.awt.Color(102, 255, 204));
// TODO add your handling code here:
    }//GEN-LAST:event_jButtonContinuarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Portada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Portada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Portada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Portada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Portada().setVisible(true);
            }
        });
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button jButtonContinuar;
    private javax.swing.JPanel jPanelFondo;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
