/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misframes;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import misclases.MySqlConn;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author elimtzxd
 */
public class TotalHab extends javax.swing.JFrame {
private MySqlConn conn;
        
    private int contadors=0, contadord=0, contadort=0;
    private int sencilla, doble, triple;
    private int numerohab[]=new int[3];
    
    /**
     * Creates new form TotalHab
     */
    public TotalHab() {
        initComponents();
         this.setSize(1020, 640);
        this.setMinimumSize(new Dimension(1020,640));
        this.setLocationRelativeTo(null);
     
    }

    public TotalHab(MySqlConn conn) {
        this.conn = conn;
        initComponents();
        mostrarGrafica();
         this.setSize(1020, 640);
        this.setMinimumSize(new Dimension(1020,640));
        this.setLocationRelativeTo(null);
     
    }
 public void mostrarGrafica(){
        
        ConsultaTotalHab();
        Llenar();
        
        DefaultCategoryDataset datos= new DefaultCategoryDataset();
        datos.addValue(this.numerohab[0], "Sencilla", "Sencilla");
        datos.addValue(this.numerohab[1], "Doble", "Doble");
        datos.addValue(this.numerohab[2], "Triple", "Triple");
        JFreeChart graficos=ChartFactory.createBarChart3D("TOTAL DE HABITACIONES", "Tipos de habitacion", "Número de habitaciones", datos, PlotOrientation.VERTICAL, true, true, false);
        ChartPanel mypanel=new ChartPanel(graficos);
        mypanel.setPreferredSize(new Dimension(jPanel1.getSize().width,jPanel1.getSize().height));
        //jPanel1.setLayout(new BorderLayout());
        jPanel1.add(mypanel,BorderLayout.CENTER);
       // pack();
        //repaint();
    }
     
    
    private void ConsultaTotalHab(){
    String query="select * from contadoreshab where doble='" +11+"'";
        this.conn.Consult(query);
        int n=0;
        try{
            this.conn.rs.last();
            n=this.conn.rs.getRow();
            this.conn.rs.first();
        }catch(Exception e){
            System.out.println("Error 1");
        }
        
                try{
                   this.sencilla=conn.rs.getInt(1);
                   this.doble=conn.rs.getInt(2);
                   this.triple=conn.rs.getInt(3);
                }catch(Exception e){
                    System.out.println("Error 2");
                
        }
}    
    private void Llenar(){
        
        this.numerohab[0]= this.sencilla ;
        this.numerohab[1]=this.doble ;
        this.numerohab[2]=this.triple;
       /* System.out.println(this.porcentaje[0]);
        System.out.println(this.porcentaje[1]);
        System.out.println(this.porcentaje[2]);
        System.out.println(this.contadors);
        System.out.println(this.contadord);
        System.out.println(this.contadort);
        System.out.println(this.sencilla);
        System.out.println(this.doble);
        System.out.println(this.triple); */
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Regresa.png"))); // NOI18N
        jButton1.setText("Regresar");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jPanel2.add(jButton1);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        this.jButton1.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        this.jButton1.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        // TODO add your handling code here:
        this.dispose();
        new MenuConsultas().setVisible(true);
    }//GEN-LAST:event_jButton1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TotalHab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TotalHab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TotalHab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TotalHab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TotalHab( new MySqlConn()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
