/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misframes;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import misclases.Cliente;
import static misclases.Hotel.habitaciones;

/**
 *
 * @author Hp
 */
public class Voucher extends javax.swing.JFrame {
    private Font font,font1;
    private Cliente cliente;
    private int tipo,pos;
    /**
     * Creates new form Voucher
     */
    public Voucher() {
        iniciarFonts();
        initComponents();
        this.jButtonContinuar.setFont(font);
        this.jLabelVoucher.setFont(font1);
        this.setTitle("Voucher Del Check In");
        this.setSize(605, 690);
        this.setMinimumSize(new Dimension(605,690));
        this.setLocationRelativeTo(null);
    }

    public Voucher(Cliente cliente, int ti, int posi) {
        this.cliente = cliente;
        this.tipo = ti;
        this.pos = posi;
        
        iniciarFonts();
        initComponents();
        this.jButtonContinuar.setFont(font);
        this.jLabelVoucher.setFont(font1);
        this.setTitle("Voucher Del Check In");
         this.setSize(605, 680);
        this.setMinimumSize(new Dimension(605,680));
        this.setLocationRelativeTo(null);
        llenarVoucher();
    }
    
    
    private void llenarVoucher(){
        String t="";
        System.out.println("Fecha Ingreso: "+cliente.getFechaIng()+"   Fecha Salida: "+cliente.getFechaSal());
        String hotel="\t\t HOTEL WOLFSBURG\n";
        String lema="\t El Arte De Cumplir Tu Más Altas Expectativas\n";
        String ubicacion="\t Zona Dorada #204, Los Cabos San Lucas\n\n\n";
        String nombre="Nombre del huesped: "+cliente.getNomHuesped()+"\n";
        String cdOrigen="Ciudad de Origen: "+cliente.getCdOrigen()+"\n";
        String fechaIn="Fecha de Ingreso: "+cliente.getFechaIng()+"\n";
        String fechaSal="Fechas de Salida: "+cliente.getFechaSal()+"\n";
        String numeroHab="Número de Habitación: "+habitaciones.get(pos).getNumero();
        String piso="   Piso: "+habitaciones.get(pos).getPiso()+"\n";
        int lim=0,extra=0;
        if(habitaciones.get(pos).getTipo()==1){
            lim=3; t="Sencilla";
        }else if(habitaciones.get(pos).getTipo()==2){
            lim=4; t="Doble";
        }else if(habitaciones.get(pos).getTipo()==3){
            lim=5; t="Triple";
        }
        String tipo="Tipo de Habitación: "+t;
        
        tipo+="  ( Limite "+lim+" huésped(es) )\n";
        String totOcupantes="Total de ocupantes de la habitación: "+cliente.getTotOcupantes();
        String extraPer="\nTiene "+cliente.getPersonasExtr()+" Personas Extra";
        
        String regCompleto="\n\nRegistro Completo";
        String info=hotel+lema+ubicacion+nombre+cdOrigen+fechaIn+fechaSal+
                numeroHab+piso+tipo+totOcupantes+extraPer+regCompleto;
        this.jTextAreaVoucher.setText(info);
    }
    
    private void iniciarFonts(){
        try {
            font=Font.createFont(Font.TRUETYPE_FONT, new File("src/fonts/Catskin.otf"));
            font=font.deriveFont(19f);
            font1=Font.createFont(Font.TRUETYPE_FONT, new File("src/fonts/Rose Cake.otf"));
            font1=font1.deriveFont(55f);
        } catch (FontFormatException ex) {
            Logger.getLogger(Voucher.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Voucher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void cerrarVentana(){
        this.dispose();
        new MenuPrincipal().setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaVoucher = new javax.swing.JTextArea();
        jButtonContinuar = new javax.swing.JButton();
        jLabelLinea1 = new javax.swing.JLabel();
        jLabelLinea2 = new javax.swing.JLabel();
        jLabelLinea3 = new javax.swing.JLabel();
        jLabelLinea4 = new javax.swing.JLabel();
        jLabelLinea5 = new javax.swing.JLabel();
        jLabelLinea6 = new javax.swing.JLabel();
        jLabelVoucher = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextAreaVoucher.setEditable(false);
        jTextAreaVoucher.setColumns(20);
        jTextAreaVoucher.setFont(new java.awt.Font("Consolas", 1, 15)); // NOI18N
        jTextAreaVoucher.setForeground(new java.awt.Color(153, 102, 0));
        jTextAreaVoucher.setRows(5);
        jScrollPane1.setViewportView(jTextAreaVoucher);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 210, 460, 380);

        jButtonContinuar.setBackground(new java.awt.Color(102, 0, 102));
        jButtonContinuar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Continuar.png"))); // NOI18N
        jButtonContinuar.setText("Continuar");
        jButtonContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonContinuarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonContinuarMouseExited(evt);
            }
        });
        jButtonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinuarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonContinuar);
        jButtonContinuar.setBounds(460, 600, 130, 40);

        jLabelLinea1.setBackground(new java.awt.Color(204, 153, 0));
        jLabelLinea1.setOpaque(true);
        getContentPane().add(jLabelLinea1);
        jLabelLinea1.setBounds(70, 0, 10, 80);

        jLabelLinea2.setBackground(new java.awt.Color(153, 102, 0));
        jLabelLinea2.setOpaque(true);
        getContentPane().add(jLabelLinea2);
        jLabelLinea2.setBounds(0, 70, 80, 10);

        jLabelLinea3.setBackground(new java.awt.Color(153, 0, 0));
        jLabelLinea3.setOpaque(true);
        getContentPane().add(jLabelLinea3);
        jLabelLinea3.setBounds(420, 70, 180, 10);

        jLabelLinea4.setBackground(new java.awt.Color(153, 102, 0));
        jLabelLinea4.setOpaque(true);
        getContentPane().add(jLabelLinea4);
        jLabelLinea4.setBounds(470, 140, 30, 160);

        jLabelLinea5.setBackground(new java.awt.Color(153, 0, 0));
        jLabelLinea5.setOpaque(true);
        getContentPane().add(jLabelLinea5);
        jLabelLinea5.setBounds(480, 280, 30, 170);

        jLabelLinea6.setBackground(new java.awt.Color(204, 153, 0));
        jLabelLinea6.setOpaque(true);
        getContentPane().add(jLabelLinea6);
        jLabelLinea6.setBounds(490, 420, 30, 140);

        jLabelVoucher.setForeground(new java.awt.Color(204, 153, 0));
        jLabelVoucher.setText("Voucher");
        getContentPane().add(jLabelVoucher);
        jLabelVoucher.setBounds(430, 10, 170, 60);

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoVoucher.png"))); // NOI18N
        getContentPane().add(jLabelFondo);
        jLabelFondo.setBounds(0, 0, 600, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinuarActionPerformed
        // TODO add your handling code here:
        cerrarVentana();
    }//GEN-LAST:event_jButtonContinuarActionPerformed

    private void jButtonContinuarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonContinuarMouseEntered
        // TODO add your handling code here:
        this.jButtonContinuar.setBackground(new Color(153,102,0));
    }//GEN-LAST:event_jButtonContinuarMouseEntered

    private void jButtonContinuarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonContinuarMouseExited
        // TODO add your handling code here:
        this.jButtonContinuar.setBackground(new Color(102,0,102));
    }//GEN-LAST:event_jButtonContinuarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Voucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Voucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Voucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Voucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Voucher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonContinuar;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLinea1;
    private javax.swing.JLabel jLabelLinea2;
    private javax.swing.JLabel jLabelLinea3;
    private javax.swing.JLabel jLabelLinea4;
    private javax.swing.JLabel jLabelLinea5;
    private javax.swing.JLabel jLabelLinea6;
    private javax.swing.JLabel jLabelVoucher;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaVoucher;
    // End of variables declaration//GEN-END:variables
}
